# generated by datamodel-codegen:
#   filename:  auth-contract.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, Field, RootModel, SecretStr, constr


class Model(RootModel[Any]):
    root: Any


class FaceLoginRequest(BaseModel):
    username: constr(min_length=1, max_length=100)
    photo: constr(min_length=1, max_length=2796227) = Field(
        ...,
        description="Base64 JPEG data URL captured by the browser camera; decoded image at most 2 MiB.",
    )


class SendCodeRequest(BaseModel):
    ticket: str


class LoginRequest(BaseModel):
    username: str = Field(..., examples=["dr_li"])
    password: SecretStr


class SuccessBase(BaseModel):
    code: Literal[0]
    message: str = Field(..., examples=["ok"])


class LoginData(BaseModel):
    ticket: str = Field(
        ...,
        description="One-time ticket exchanged at `/auth/verify-code`. Valid for 5 minutes.",
    )
    expires_in: int = Field(..., description="Seconds until the ticket expires.", examples=[300])


class VerifyCodeRequest(BaseModel):
    ticket: str
    code: constr(pattern=r"^[0-9]{6}$")


class Role(Enum):
    admin = "admin"
    senior = "senior"
    junior = "junior"


class TempGrantCreateRequest(BaseModel):
    grantee_id: int
    patient_no: str = Field(..., examples=["P20260001"])
    reason: constr(max_length=500)
    expire_at: AwareDatetime


class TempGrant(BaseModel):
    id: int
    grantee_id: int
    grantee_name: str | None = None
    patient_no: str = Field(
        ...,
        description="The patient the grant unlocks, named as on `Patient`. T10 defines the table\nas `temp_grant(grantee_id, patient_id, reason, expire_at, is_valid)` — that\n`patient_id` is the table's internal key, and this property is the business\nkey (`P20260001`), the only form the API exposes. A grant is always\npatient-scoped; there is no generic target type.\n",
        examples=["P20260001"],
    )
    reason: str
    granted_by: int | None = None
    expire_at: AwareDatetime = Field(
        ..., description="The scan flips `is_valid` to false once this passes."
    )
    is_valid: bool = Field(
        ...,
        description="The single validity flag. The scheduler sets it false when `expire_at`\npasses; the immediate-revocation endpoint sets it false by hand. There is\nno separate `expired` versus `revoked` state.\n",
    )
    created_at: AwareDatetime | None = None


class Page(BaseModel):
    total: int = Field(..., examples=[42])
    page: int = Field(..., examples=[1])
    size: int = Field(..., examples=[20])


class Db(Enum):
    ok = "ok"
    down = "down"
    disabled = "disabled"


class Redis(Enum):
    ok = "ok"
    down = "down"
    disabled = "disabled"


class HealthData(BaseModel):
    db: Db = Field(
        ...,
        description='"ok" when reachable, "down" when the check fails, "disabled" when no URL is configured.',
        examples=["ok"],
    )
    redis: Redis = Field(
        ...,
        description='"down" is reported with HTTP 200, not 500. See the route description.',
        examples=["ok"],
    )


class OkData(BaseModel):
    code: Literal[0]
    message: str = Field(..., examples=["ok"])
    data: dict[str, Any]


class LoginResponse(SuccessBase):
    data: LoginData


class CurrentUser(BaseModel):
    id: int
    username: str = Field(..., examples=["admin_zhang"])
    name: str = Field(..., examples=["Zhang Wei"])
    title: Role = Field(
        ...,
        description="The caller's role. Named `title` because that is the field the JWT payload\ncarries and the field T05 scenario S1 asserts on `/api/me`\n(`department=信息科`, `title=admin`). Do not rename it to `role` on the wire.\n",
    )
    department: str = Field(..., examples=["Information Technology"])


class CurrentUserResponse(SuccessBase):
    data: CurrentUser


class TempGrantResponse(SuccessBase):
    data: TempGrant


class Data(Page):
    items: list[TempGrant]


class TempGrantListResponse(SuccessBase):
    data: Data


class HealthResponse(SuccessBase):
    data: HealthData


class TokenData(BaseModel):
    access_token: str
    token_type: Literal["bearer"]
    expires_in: int = Field(..., description="Token lifetime in seconds.", examples=[7200])
    user: CurrentUser


class TokenResponse(SuccessBase):
    data: TokenData
