# generated by datamodel-codegen:
#   filename:  emr-contract.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, RootModel


class Model(RootModel[Any]):
    root: Any


class Type(Enum):
    text = "text"
    number = "number"
    date = "date"
    select = "select"
    textarea = "textarea"


class EmrField(BaseModel):
    key: str = Field(..., examples=["chief_complaint"])
    label: str = Field(..., examples=["Chief complaint"])
    type: Type = Field(..., description="The five supported types. Anything else is a 422.")
    required: bool | None = False
    options: list[str] | None = Field(None, description="Present only when `type` is `select`.")


class EmrRecordCreateRequest(BaseModel):
    patient_no: str
    template_id: int


class EmrRecordUpdateRequest(BaseModel):
    content_json: dict[str, Any]
    version: int
    revision: int = Field(
        ..., description="Independent optimistic lock incremented on every mutation."
    )


class AmendmentRequest(BaseModel):
    content_json: dict[str, Any]


class Action(Enum):
    approve = "approve"
    reject = "reject"


class ReviewRequest(BaseModel):
    action: Action
    comment: str | None = Field(None, description="Required when `action` is `reject`.")


class OrderType(Enum):
    drug = "drug"
    lab = "lab"
    exam = "exam"


class FieldsJson(BaseModel):
    fields: list[EmrField] = Field(..., min_length=1)


class EmrTemplateWriteRequest(BaseModel):
    name: str = Field(..., examples=["Admission note"])
    description: str | None = None
    is_active: bool | None = True
    fields_json: FieldsJson


class OrderItemInput(BaseModel):
    order_type: OrderType
    drug_code: str | None = Field(None, examples=["AMOX500"])
    dose: str | None = Field(
        None,
        description="Required when `order_type` is `drug`; omitted for `lab` and `exam`.",
        examples=["0.5g"],
    )
    frequency: str | None = Field(None, examples=["tid"])
    route: str | None = None


class OrderCreateRequest(BaseModel):
    record_id: int
    override_reason: str | None = Field(
        None,
        description="Optional. Accepted when any item validates as `warning`; stored on every item it covers.",
    )
    items: list[OrderItemInput] = Field(..., min_length=1)


class OrderValidateRequest(BaseModel):
    patient_no: str
    items: list[OrderItemInput] = Field(..., min_length=1)
