from datetime import UTC, date, datetime

from sqlalchemy import (
    JSON,
    BigInteger,
    Boolean,
    Date,
    DateTime,
    ForeignKey,
    LargeBinary,
    String,
    Text,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class Department(Base):
    __tablename__ = "departments"
    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(100), unique=True)


class Role(Base):
    __tablename__ = "roles"
    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(50), unique=True)


class User(Base):
    __tablename__ = "users"
    id: Mapped[int] = mapped_column(primary_key=True)
    username: Mapped[str] = mapped_column(String(100), unique=True)
    name: Mapped[str] = mapped_column(String(100))
    status: Mapped[str] = mapped_column(String(20), default="active", server_default="active")
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(UTC)
    )
    role: Mapped[Role] = relationship(lazy="joined")
    department: Mapped[Department] = relationship(lazy="joined")
    email: Mapped[str] = mapped_column(String(254), unique=True)
    password_hash: Mapped[str] = mapped_column(String(255))
    role_id: Mapped[int] = mapped_column(ForeignKey("roles.id"))
    department_id: Mapped[int] = mapped_column(ForeignKey("departments.id"))


class Patient(Base):
    __tablename__ = "patients"
    id: Mapped[int] = mapped_column(primary_key=True)
    # "P<year><sequence>", generated by the API. Nullable only because SQLite cannot
    # add a NOT NULL column to a populated table without a default: the migration
    # backfills existing rows and the unique index keeps the values unique.
    patient_no: Mapped[str] = mapped_column(String(20), unique=True, index=True, nullable=True)
    name: Mapped[str] = mapped_column(String(100), index=True)
    gender: Mapped[str] = mapped_column(String(10), default="unknown")
    birth_date: Mapped[date | None] = mapped_column(Date)
    department_id: Mapped[int] = mapped_column(ForeignKey("departments.id"))
    notes: Mapped[str] = mapped_column(Text, default="")
    phone_enc: Mapped[str | None] = mapped_column(String(255))
    id_card_enc: Mapped[str | None] = mapped_column(String(255))
    # Canonical ",tag,tag," form, so a tag match cannot hit a substring.
    symptom_tags: Mapped[str] = mapped_column(String(500), default="")
    admitted_at: Mapped[date | None] = mapped_column(Date)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(UTC), index=True
    )
    # Soft delete: reads filter this out, while allergies and the audit trail stay put.
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), index=True)

    department: Mapped[Department] = relationship(lazy="joined")


class Allergy(Base):
    __tablename__ = "allergies"
    id: Mapped[int] = mapped_column(primary_key=True)
    patient_id: Mapped[int] = mapped_column(
        ForeignKey("patients.id", ondelete="CASCADE"), index=True
    )
    # A code from app.allergies.DICTIONARY, such as PENICILLIN: the order-validation
    # engine compares codes against Drug.contraindications, so names never go here.
    allergen: Mapped[str] = mapped_column(String(50))
    allergy_type: Mapped[str] = mapped_column(String(20), default="other")
    severity: Mapped[str] = mapped_column(String(20), default="moderate")
    reaction: Mapped[str | None] = mapped_column(String(255))
    recorded_at: Mapped[date] = mapped_column(Date)


class AuditLog(Base):
    __tablename__ = "audit_logs"
    id: Mapped[int] = mapped_column(primary_key=True)
    action: Mapped[str] = mapped_column(String(50), index=True)
    patient_id: Mapped[int | None] = mapped_column()  # Preserve deleted references.
    user_id: Mapped[int | None] = mapped_column(index=True)
    # Snapshotted rather than joined: the log has to say who acted at the time,
    # and a join would let a later rename or deletion rewrite the past. The
    # append-only trigger means this can never be backfilled, so rows written
    # before this column existed keep NULL for good.
    username: Mapped[str | None] = mapped_column(String(100))
    ip: Mapped[str | None] = mapped_column(String(45))
    method: Mapped[str | None] = mapped_column(String(10))
    path: Mapped[str | None] = mapped_column(String(500))
    object_type: Mapped[str | None] = mapped_column(String(50))
    object_id: Mapped[str | None] = mapped_column(String(100))
    result: Mapped[str | None] = mapped_column(String(20))
    status_code: Mapped[int | None] = mapped_column()
    # T14 scenario S2 reads the deleted allergen's name back out of this column.
    detail: Mapped[dict | None] = mapped_column(JSON)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(UTC), index=True
    )


class TempGrant(Base):
    __tablename__ = "temp_grant"
    id: Mapped[int] = mapped_column(primary_key=True)
    grantee_id: Mapped[int] = mapped_column(ForeignKey("users.id"), index=True)
    patient_id: Mapped[int] = mapped_column(ForeignKey("patients.id"), index=True)
    reason: Mapped[str] = mapped_column(String(500))
    granted_by: Mapped[int] = mapped_column(ForeignKey("users.id"))
    expire_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), index=True)
    is_valid: Mapped[bool] = mapped_column(Boolean, default=True, index=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(UTC)
    )
    grantee: Mapped[User] = relationship(foreign_keys=[grantee_id], lazy="joined")
    patient: Mapped[Patient] = relationship(lazy="joined")


class Passkey(Base):
    __tablename__ = "passkeys"
    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id"), index=True)
    credential_id: Mapped[bytes] = mapped_column(LargeBinary(1024))
    credential_hash: Mapped[str] = mapped_column(String(64), unique=True)
    public_key: Mapped[bytes] = mapped_column(LargeBinary(2048))
    sign_count: Mapped[int] = mapped_column(BigInteger)
