# generated by datamodel-codegen:
#   filename:  user-contract.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    SecretStr,
    constr,
)


class Model(RootModel[Any]):
    root: Any


class Role(Enum):
    admin = "admin"
    senior = "senior"
    junior = "junior"


class Status(Enum):
    active = "active"
    disabled = "disabled"


class UserUpdateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str | None = Field(
        None, description="Display name, must not be blank. / 显示名，不可为空白。\n"
    )
    title: Role | None = None
    department: str | None = Field(
        None,
        description="Department **name**. An unregistered name is a 422. / 科室**名**；未登记则 422。\n",
    )
    status: Status | None = Field(
        None,
        description="Setting `disabled` refuses that account's already-issued tokens from the next\nrequest onwards -- no logout needed, no token blacklist involved.\n/ 置为 `disabled` 后，该账号已签发的 token 从下一个请求起即被拒，\n无需注销、也不涉及 token 黑名单。\n",
    )


class SuccessBase(BaseModel):
    code: Literal[0]
    message: str = Field(..., examples=["ok"])


class CurrentUser(BaseModel):
    id: int
    username: str = Field(..., examples=["admin_zhang"])
    name: str = Field(..., examples=["Zhang Wei"])
    title: Role = Field(
        ...,
        description="The caller's role. Named `title` because that is the field the JWT payload\ncarries and the field T05 scenario S1 asserts on `/api/me`\n(`department=Information Technology`, `title=admin`). Do not rename it to `role`\non the wire.\n",
    )
    department: str = Field(..., examples=["Information Technology"])


class AccountStatus(Enum):
    pending = "pending"
    active = "active"
    disabled = "disabled"


class Page(BaseModel):
    total: int = Field(..., examples=[42])
    page: int = Field(..., examples=[1])
    size: int = Field(..., examples=[20])


class Datum(BaseModel):
    code: Role
    label: str = Field(..., examples=["Senior physician"])


class RoleListResponse(SuccessBase):
    data: list[Datum]


class UserCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    username: str = Field(
        ...,
        description="Unique, compared case-insensitively. / 唯一，比对不区分大小写。\n",
    )
    password: SecretStr = Field(
        ...,
        description="At least 8 characters and at most 72 **UTF-8 bytes** -- that upper bound is bcrypt's,\nnot a policy choice, and a longer secret is refused rather than silently truncated.\n/ 至少 8 个字符，且不超过 72 个 **UTF-8 字节**——上限来自 bcrypt 本身，\n超长密码会被拒而不是静默截断。\n",
    )
    name: str = Field(..., description="Display name, must not be blank. / 显示名，不可为空白。\n")
    email: constr(pattern=r"^[^\s@]+@[^\s@]+\.[^\s@]+$", min_length=3, max_length=254) = Field(
        ...,
        description="Unique, compared case-insensitively. / 唯一，比对不区分大小写。\n",
    )
    title: Role
    department: str = Field(
        ...,
        description="Department **name**. An unregistered name is a 422. / 科室**名**；未登记则 422。\n",
    )


class User(CurrentUser):
    email: constr(pattern=r"^[^\s@]+@[^\s@]+\.[^\s@]+$", min_length=3, max_length=254) | None = (
        Field(None, description="Administrator-only. / 仅管理员可见。\n")
    )
    status: AccountStatus | None = Field(
        None,
        description="Administrator-only. A `disabled` account is refused even while holding a\nvalid token. / 仅管理员可见；`disabled` 的账号即使持有有效 token 也会被拒。\n",
    )
    created_at: AwareDatetime | None = Field(
        None,
        description="Administrator-only, always UTC and always offset-aware.\n/ 仅管理员可见，UTC，且始终带时区偏移。\n",
    )


class Data(Page):
    items: list[User]


class UserListResponse(SuccessBase):
    data: Data


class UserResponse(SuccessBase):
    data: User
