"""T12 audit actor name and query indexes.

Deliberately not wrapped in `batch_alter_table`. On SQLite a batch operation
rebuilds the table -- create, copy, drop, rename -- and dropping the table drops
the append-only triggers that `c0311060809b` installed. Silently: Alembic's
batch mode recreates indexes and constraints, not triggers, so the loss shows up
as "the audit log can be edited again" and not as an error. A nullable
`ADD COLUMN` is native on both SQLite and MySQL, so nothing here needs a rebuild.

`username` also cannot be backfilled: the same trigger rejects the UPDATE that
would do it. Rows written before this revision keep NULL for good, which is
acceptable only because they are development noise.
"""

import sqlalchemy as sa
from alembic import op

revision = "786395e6a0ba"
down_revision = "c0311060809b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("audit_logs", sa.Column("username", sa.String(length=100), nullable=True))
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_column("audit_logs", "username")
    # ### end Alembic commands ###
