"""add M4 records prescriptions and rules"""

import sqlalchemy as sa
from alembic import op

revision = "7ad4cb527bd2"
down_revision = "f4b7c1e93a20"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drug",
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("spec", sa.String(), nullable=False),
        sa.Column("default_frequency", sa.String(), nullable=False),
        sa.Column("contraindications", sa.JSON(), nullable=False),
        sa.Column("dose_min", sa.String(), nullable=False),
        sa.Column("dose_max", sa.String(), nullable=False),
        sa.Column("dose_rule", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "emr_template",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("fields_json", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "emr_record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("template_snapshot", sa.JSON(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("content_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("reviewer_id", sa.Integer(), nullable=True),
        sa.Column("review_comment", sa.String(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["emr_template.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_emr_record_author_id"), "emr_record", ["author_id"], unique=False)
    op.create_index(op.f("ix_emr_record_patient_id"), "emr_record", ["patient_id"], unique=False)
    op.create_index(op.f("ix_emr_record_status"), "emr_record", ["status"], unique=False)
    op.create_index(
        op.f("ix_emr_record_submitted_at"), "emr_record", ["submitted_at"], unique=False
    )
    op.create_table(
        "emr_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_json", sa.JSON(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["emr_record.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("record_id", "version"),
    )
    op.create_index(op.f("ix_emr_version_record_id"), "emr_version", ["record_id"], unique=False)
    op.create_table(
        "medical_order",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("doctor_id", sa.Integer(), nullable=False),
        sa.Column("order_type", sa.String(length=20), nullable=False),
        sa.Column("content_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("validation_status", sa.String(length=20), nullable=False),
        sa.Column("validation_detail", sa.JSON(), nullable=False),
        sa.Column("override_reason", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["emr_record.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_medical_order_record_id"), "medical_order", ["record_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_medical_order_record_id"), table_name="medical_order")
    op.drop_table("medical_order")
    op.drop_index(op.f("ix_emr_version_record_id"), table_name="emr_version")
    op.drop_table("emr_version")
    op.drop_index(op.f("ix_emr_record_submitted_at"), table_name="emr_record")
    op.drop_index(op.f("ix_emr_record_status"), table_name="emr_record")
    op.drop_index(op.f("ix_emr_record_patient_id"), table_name="emr_record")
    op.drop_index(op.f("ix_emr_record_author_id"), table_name="emr_record")
    op.drop_table("emr_record")
    op.drop_table("emr_template")
    op.drop_table("drug")
    # ### end Alembic commands ###
