"""B W2 W3 orders chat health and reminders"""

import sqlalchemy as sa
from alembic import op

revision = "bd9e76dbea39"
down_revision = "c0311060809b"
branch_labels = None
depends_on = None


def upgrade():
    # Main M4 and the older branch independently used this name. Preserve both.
    order_table = (
        "legacy_medical_order"
        if sa.inspect(op.get_bind()).has_table("medical_order")
        else "medical_order"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consultation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("doctor_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("last_message", sa.String(length=200), nullable=False),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_consultation_patient_id"), "consultation", ["patient_id"], unique=False
    )
    op.create_index(op.f("ix_consultation_status"), "consultation", ["status"], unique=False)
    op.create_table(
        "health_plan",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("doctor_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("goals", sa.Text(), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("entries", sa.JSON(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_health_plan_patient_id"), "health_plan", ["patient_id"], unique=False)
    op.create_table(
        order_table,
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("doctor_id", sa.Integer(), nullable=False),
        sa.Column("order_type", sa.String(length=20), nullable=False),
        sa.Column("content_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("validation_status", sa.String(length=20), nullable=False),
        sa.Column("validation_detail", sa.JSON(), nullable=False),
        sa.Column("override_reason", sa.String(length=1000), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f(f"ix_{order_table}_patient_id"), order_table, ["patient_id"], unique=False)
    op.create_index(op.f(f"ix_{order_table}_record_id"), order_table, ["record_id"], unique=False)
    op.create_table(
        "consult_message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("consultation_id", sa.Integer(), nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.String(length=64), nullable=True),
        sa.Column("sender_type", sa.String(length=20), nullable=False),
        sa.Column("sender_name", sa.String(length=100), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("image_url", sa.String(length=255), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["consultation_id"],
            ["consultation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("consultation_id", "sender_id", "client_id", name="uq_message_retry"),
    )
    op.create_index(
        op.f("ix_consult_message_consultation_id"),
        "consult_message",
        ["consultation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consult_message_sent_at"), "consult_message", ["sent_at"], unique=False
    )
    op.create_table(
        "image_upload",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=100), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("consultation_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["consultation_id"],
            ["consultation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("filename"),
    )
    op.create_table(
        "reminder_rule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("doctor_id", sa.Integer(), nullable=False),
        sa.Column("health_plan_id", sa.Integer(), nullable=True),
        sa.Column("rtype", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("cron_expr", sa.String(length=100), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["health_plan_id"],
            ["health_plan.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reminder_rule_doctor_id"), "reminder_rule", ["doctor_id"], unique=False
    )
    op.create_index(
        op.f("ix_reminder_rule_health_plan_id"), "reminder_rule", ["health_plan_id"], unique=False
    )
    op.create_index(
        op.f("ix_reminder_rule_patient_id"), "reminder_rule", ["patient_id"], unique=False
    )
    op.create_table(
        "reminder_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rule_id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("doctor_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("done", sa.Boolean(), nullable=False),
        sa.Column("done_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["reminder_rule.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rule_id", "due_at", name="uq_reminder_due"),
    )
    op.create_index(op.f("ix_reminder_log_doctor_id"), "reminder_log", ["doctor_id"], unique=False)
    op.create_index(
        op.f("ix_reminder_log_patient_id"), "reminder_log", ["patient_id"], unique=False
    )
    op.create_index(op.f("ix_reminder_log_rule_id"), "reminder_log", ["rule_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    order_table = (
        "legacy_medical_order"
        if sa.inspect(op.get_bind()).has_table("legacy_medical_order")
        else "medical_order"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reminder_log_rule_id"), table_name="reminder_log")
    op.drop_index(op.f("ix_reminder_log_patient_id"), table_name="reminder_log")
    op.drop_index(op.f("ix_reminder_log_doctor_id"), table_name="reminder_log")
    op.drop_table("reminder_log")
    op.drop_index(op.f("ix_reminder_rule_patient_id"), table_name="reminder_rule")
    op.drop_index(op.f("ix_reminder_rule_health_plan_id"), table_name="reminder_rule")
    op.drop_index(op.f("ix_reminder_rule_doctor_id"), table_name="reminder_rule")
    op.drop_table("reminder_rule")
    op.drop_table("image_upload")
    op.drop_index(op.f("ix_consult_message_sent_at"), table_name="consult_message")
    op.drop_index(op.f("ix_consult_message_consultation_id"), table_name="consult_message")
    op.drop_table("consult_message")
    op.drop_index(op.f(f"ix_{order_table}_record_id"), table_name=order_table)
    op.drop_index(op.f(f"ix_{order_table}_patient_id"), table_name=order_table)
    op.drop_table(order_table)
    op.drop_index(op.f("ix_health_plan_patient_id"), table_name="health_plan")
    op.drop_table("health_plan")
    op.drop_index(op.f("ix_consultation_status"), table_name="consultation")
    op.drop_index(op.f("ix_consultation_patient_id"), table_name="consultation")
    op.drop_table("consultation")
    # ### end Alembic commands ###
